# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/fg/pcileech-fpga/CaptainDMA/75t484_x1/pcileech_75t484_x1/pcileech_75t484_x1.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci
# IP: The module: 'fifo_34_34' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fg/pcileech-fpga/CaptainDMA/75t484_x1/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/fifo_34_34/fifo_34_34.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/fg/pcileech-fpga/CaptainDMA/75t484_x1/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/fifo_34_34/fifo_34_34_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/fg/pcileech-fpga/CaptainDMA/75t484_x1/pcileech_75t484_x1/pcileech_75t484_x1.srcs/sources_1/ip/fifo_34_34/fifo_34_34.xci
# IP: The module: 'fifo_34_34' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/fg/pcileech-fpga/CaptainDMA/75t484_x1/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/fifo_34_34/fifo_34_34.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/fg/pcileech-fpga/CaptainDMA/75t484_x1/pcileech_75t484_x1/pcileech_75t484_x1.gen/sources_1/ip/fifo_34_34/fifo_34_34_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_34_34'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
